---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: monitoring
  name: adot-tempo
spec:
  mode: deployment
  replicas: 1
  serviceAccount: adot-tempo
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi 

  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    exporters:
      otlp:
        endpoint: "http://tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
    
    service:
      pipelines:
        traces:
          receivers:
            - otlp
          exporters:
            - otlp
