---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: adot-collector-onebyone-tempo

---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: monitoring
  name: adot-collector-onebyone-tempo
spec:
  mode: deployment
  replicas: 1
  serviceAccount: adot-collector-onebyone-tempo
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi 

  config: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    
    exporters:
      otlp:
        endpoint: "http://tempo.monitoring.svc.cluster.local:4318"
        tls:
          insecure: true
   
    extensions:
      health_check:

    service:
      extensions:
      - health_check
      pipelines:
        traces:
          receivers:
          - otlp
          exporters:
          - otlp

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  namespace: monitoring
  name: adot-instrumentation-onebyone-tempo
spec:
  exporter:
    endpoint: "http://adot-collector-onebyone-tempo-collector.monitoring.svc.cluster.local:4318"
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: always_on
