apiVersion: v1
kind: Namespace
metadata:
  name: adot-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: adot-collector
  name: adot-log-os
  annotations:
    eks.amazonaws.com/role-arn: ${os_role_arn}
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: adot-collector
  name: adot-trace-os
spec:
  mode: deployment
  replicas: 1
  serviceAccount: adot-trace-os
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi

  config: |
    extensions:
      health_check:
      sigv4auth:
        region: ${aws_region}
        service: "osis"

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    exporters:
      otlphttp:
        traces_endpoint: "https://${os_trace_endpoint}/v1/traces"
        auth:
          authenticator: sigv4auth
        compression: none
    
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
    
    service:
      extensions: [health_check, sigv4auth]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [otlphttp]
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: adot-trace-os
  namespace: app
spec:
  exporter:
    endpoint: http://adot-trace-os-collector.adot-collector.svc.cluster.local:4318
  propagators:
  - tracecontext
  - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    # temp
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.43b0
    env:
    - name: OTEL_METRICS_EXPORTER
      value: none
