apiVersion: v1
kind: Namespace
metadata:
  name: adot-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: adot-collector
  name: adot-traced-tempo
---
apiVersion: v1
kind: Service
metadata:
  namespace: adot-collector
  name: adot-traced-tempo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adot-traced-tempo-collector
  ports:
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: adot-collector
  name: adot-traced-tempo
spec:
  config: |
    extensions:
      health_check:

    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
  
    processors:
      batch/traces:
        timeout: 60s
        send_batch_size: 50
  
    exporters:
      otlphttp:
        endpoint: http://tempo.observability:4318
        tls:
          insecure: true
    
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch/traces]
          exporters: [otlphttp]
