---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: adot-collector-tempo

---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: monitoring
  name: adot-collector-tempo
spec:
  mode: deployment
  replicas: 1
  serviceAccount: adot-collector-tempo
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi 

  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    exporters:
      otlp:
        endpoint: "http://tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
   
    extensions:
      health_check:

    service:
      extensions:
      - health_check
      pipelines:
        traces:
          receivers:
          - otlp
          exporters:
          - otlp
