apiVersion: v1
kind: Namespace
metadata:
  name: adot-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: adot-collector
  name: adot-logd-loki
---
apiVersion: v1
kind: Service
metadata:
  namespace: adot-collector
  name: adot-logd-loki
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: adot-logd-loki-collector
  ports:
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  namespace: adot-collector
  name: adot-logd-loki
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  hostNetwork: false
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi
  
  env:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: HOST_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: K8S_NAMESPACE
    valueFrom:
       fieldRef:
         fieldPath: metadata.namespace
  
  config: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
    
    processors:
      batch:
    
    exporters:
      otlphttp:
        logs_endpoint: "http://loki.observability:3100/otlp/v1/logs"
        compression: none
    
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
